### ISSUE TITLE
Editdist 3 needed to get two edits

### ISSUE THREAD

**Issue by snomos** [giellalt/lang-tkl#1]
Cf 7699cd6b96a6e1793f248b105c8d3c0f7997f597

@flammie could you have a look at why? It should not be like this. Example test cases:

```sh
echo Fakahauaga |divvunspell suggest --archive tools/spellcheckers/tkl.zhfst             
Reading from stdin...
Input: Fakahauaga		[INCORRECT]
Fakahāuāga		25.509945
Fakahalaga		33.875813
Fakapaiaga		46.896236
Fakahaga		50.19149
Fakahahana		52.896236
Fakamalaga		52.896236
Fakamataga		52.896236
Fakataga		63.657562
Fakamanuiaga		63.805195
Fakamatala		64.22209
```

The first suggestion is the expected one. With editdist=2, no such suggestion is generated. This can be confirmed with:

```sh
 echo Fakahauaga | hfst-lookup -q tools/spellcheckers/errmodel.default.hfst | less
```

and then search for `Fakahāuāga` in the generated list.

@Trondtr FYI.

**Comment by flammie** [comment]
it seems like the regex version of edit dist at least doesn't manage to hop over letter not in the regex- (e.g. capital F), this is a common problem with wild cards and alphabets and xerox regexes. Updated giella-core will just smush in extracted sigmastar from alphabet.

**Comment by snomos** [comment]
Confirmed. This is now the output with editdist 2:

```sh
echo Fakahauaga |divvunspell suggest --archive tools/spellcheckers/tkl.zhfst  
Reading from stdin...
Input: Fakahauaga		[INCORRECT]
Fakahāuāga		25.509945
Fakahalaga		33.875813
Fakapaiaga		46.896236
Fakahaga		50.19149
Fakahahana		52.896236
Fakamalaga		52.896236
Fakamataga		52.896236
```
